site_name: Robostorm
site_dir: /var/www/robostorm/public_html
repo_url: https://github.com/Robostorm
theme: flatly
theme_dir: custom_theme
site_favicon: icon.png
pages:
- Home: 'index.md'
- Projects:
    - 'Aquabot': 'aquabot.md'
    - 'Aquaponics': 'aquaponics.md'
    - '3D Printing': '3dprinter.md'
    - 'Other Projects': 'projects.md'
- Battlebots: 'battlebots.md'
- FTC: 'ftc.md'
- About Us:
    - 'Contact Us': 'contact.md'
    - 'History': 'history.md'
